### ISSUE TITLE
Download albums - background processing

### ISSUE THREAD

**Issue by ItsMePN** [aakashthakkar/FacebookMemories#4]
When I select multiple albums and click 'Download selected albums' button in left sidebar, you have shown a nice dialog box with 'Hide' button. If I click that I am unaware for some time whether my download is actually being processed in the background or not.

After some time, it did show me another dialog box with download link but I suggest when user clicks on 'hide' button, you add a message on top saying "Your download is being processed in the background and will be ready in few minutes..."

**Comment by aakashthakkar** [comment]
It has been resolved. Kindly check out the live demo <a href="http://rtcamp-thakkaraakash.rhcloud.com">here.</a>
